<template>
  <div class="view-content font-inter">

    <!-- Action Row -->
    <div class="action-row">
      <div class="filter-group">
        <label class="filter-label">Report Type</label>
        <pv-select v-model="selectedReport" :options="reportTypes" placeholder="Select report" class="filter-select" />
      </div>
      <div class="filter-group">
        <label class="filter-label">Period</label>
        <pv-select v-model="selectedPeriod" :options="periods" placeholder="Select period" class="filter-select" />
      </div>
      <div class="ml-auto flex gap-2">
        <pv-button label="Export PDF" icon="pi pi-file-pdf" class="export-btn pdf" @click="exportPDF" />
      </div>
    </div>

    <!-- Report Preview Card -->
    <div class="report-card">
      <!-- Report Header -->
      <div class="report-header">
        <div class="report-brand">
          <img src="/logo.png" alt="Buildline" class="report-logo" />
          <div>
            <h2 class="report-company">Buildline</h2>
            <span class="report-subtitle">Digital Construction Logistics</span>
          </div>
        </div>
        <div class="report-meta">
          <h3 class="report-type">{{ selectedReport }} Report</h3>
          <span class="report-date">Generated: {{ currentDate }}</span>
          <span class="report-period">Period: {{ selectedPeriod }}</span>
        </div>
      </div>

      <!-- Report KPIs -->
      <div class="report-kpi-row">
        <div class="report-kpi">
          <span class="report-kpi-value">{{ inventoryStore.totalItems }}</span>
          <span class="report-kpi-label">Total Items</span>
        </div>
        <div class="report-kpi">
          <span class="report-kpi-value" style="color: #3D9F7D;">Active</span>
          <span class="report-kpi-label">System Status</span>
        </div>
        <div class="report-kpi">
          <span class="report-kpi-value">${{ analyticsStore.totalSpent.toLocaleString() }}</span>
          <span class="report-kpi-label">Total Spent</span>
        </div>
        <div class="report-kpi">
          <span class="report-kpi-value">{{ projectCount }}</span>
          <span class="report-kpi-label">Active Projects</span>
        </div>
      </div>

      <!-- Report Table -->
      <div class="report-table-section">
        <h4 class="report-section-title">Material Inventory Details</h4>
        <table class="report-table">
          <thead>
            <tr>
              <th>Item ID</th>
              <th>Material</th>
              <th>Project</th>
              <th>Category</th>
              <th class="text-right">Stock</th>
              <th class="text-right">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in reportItems" :key="item.id">
              <td>{{ item.sku }}</td>
              <td class="font-semibold">{{ item.name }}</td>
              <td>{{ item.project }}</td>
              <td>{{ item.category }}</td>
              <td class="text-right font-bold">{{ item.currentStock }}</td>
              <td class="text-right">
                <span :class="['report-status', getStatusClass(item)]">{{ getStatusLabel(item) }}</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Report Footer -->
      <div class="report-footer">
        <p>This is an automated document generated by Buildline Logistics Platform.</p>
        <p>Confidential — For internal use only.</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { useInventoryStore } from '../../../inventory/application/inventory.store.js';
import { useAnalyticsStore } from '../../application/analytics.store.js';

const inventoryStore = useInventoryStore();
const analyticsStore = useAnalyticsStore();

const selectedReport = ref('Inventory Summary');
const selectedPeriod = ref('May 2026');
const reportTypes = ['Inventory Summary', 'Purchase History', 'Budget Overview', 'Supplier Performance'];
const periods = ['May 2026', 'April 2026', 'Q1 2026', 'Q2 2026', 'Full Year 2026'];

onMounted(async () => {
  await Promise.all([
    inventoryStore.fetchInventory(),
    analyticsStore.fetchBudgets()
  ]);
});

const currentDate = computed(() => new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }));
const reportItems = computed(() => inventoryStore.inventoryList);
const projectCount = computed(() => {
  const projects = new Set(inventoryStore.inventoryList.map(i => i.project));
  return projects.size;
});

const getStatusLabel = (item) => {
  if (item.currentStock === 0) return 'Out of Stock';
  if (item.currentStock <= item.minStock) return 'Low Stock';
  return 'In Stock';
};

const getStatusClass = (item) => {
  if (item.currentStock === 0) return 'report-status-danger';
  if (item.currentStock <= item.minStock) return 'report-status-warn';
  return 'report-status-ok';
};

const exportPDF = () => {
  window.print();
};
</script>

<style scoped>
.view-content { width: 100%; }

.action-row { display: flex; align-items: flex-end; gap: 16px; margin-bottom: 24px; }
.filter-group { display: flex; flex-direction: column; gap: 6px; }
.filter-label { font-size: 11px; font-weight: 700; color: #6B7280; text-transform: uppercase; letter-spacing: 0.03em; }
.export-btn { border-radius: 12px !important; font-weight: 700 !important; font-size: 13px !important; padding: 10px 20px !important; }
.export-btn.pdf { background: #E02424 !important; border-color: #E02424 !important; }

.report-card { background: white; border-radius: 20px; box-shadow: 0 1px 8px rgba(0, 0, 0, 0.04); padding: 48px; }

.report-header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 24px; border-bottom: 2px solid #1E293B; margin-bottom: 28px; }
.report-brand { display: flex; align-items: center; gap: 16px; }
.report-logo { height: 52px; width: auto; object-fit: contain; }
.report-company { font-size: 22px; font-weight: 800; color: #1E293B; margin: 0; }
.report-subtitle { font-size: 11px; font-weight: 600; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.05em; }
.report-meta { text-align: right; display: flex; flex-direction: column; gap: 2px; }
.report-type { font-size: 16px; font-weight: 800; color: #1E293B; margin: 0; }
.report-date, .report-period { font-size: 12px; color: #64748B; }

.report-kpi-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }
.report-kpi { padding: 20px; border: 1px solid #F1F5F9; border-radius: 12px; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center; gap: 6px; }
.report-kpi-value { font-size: 26px; font-weight: 800; color: #1E293B; }
.report-kpi-label { font-size: 12px; font-weight: 600; color: #94A3B8; }

.report-section-title { font-size: 14px; font-weight: 800; color: #374151; margin: 0 0 16px 0; }
.report-table { width: 100%; border-collapse: collapse; table-layout: fixed; }
.report-table th { text-align: center; font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.03em; padding: 12px 16px; border-bottom: 1px solid #E2E8F0; }
.report-table td { padding: 14px 16px; font-size: 13px; color: #374151; border-bottom: 1px solid #F8FAFC; text-align: center; }
.report-table tbody tr:hover { background: #FAFBFC; }

.report-status { font-size: 11px; font-weight: 700; padding: 4px 10px; border-radius: 4px; white-space: nowrap; }
.report-status-ok { background: #EAF8F0; color: #3D9F7D; }
.report-status-warn { background: #FEF6E5; color: #D97706; }
.report-status-danger { background: #FEECEB; color: #E02424; }

.report-footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #F1F5F9; text-align: center; }
.report-footer p { margin: 0; font-size: 11px; color: #94A3B8; line-height: 1.8; }

:deep(.filter-select) { min-width: 180px; border: 1px solid #E5E7EB !important; border-radius: 12px !important; background: white !important; }
</style>

<!-- Unscoped print styles — only report-specific rules (layout hides sidebar/header itself) -->
<style>
@media print {
  .action-row { display: none !important; }
  body { background: white !important; overflow: visible !important; }
  main {
    padding: 0 !important;
    margin: 0 !important;
    overflow: visible !important;
    width: 100% !important;
  }
  .view-content { padding: 0 !important; }
  .report-card {
    box-shadow: none !important;
    border: none !important;
    border-radius: 0 !important;
    margin: 0 !important;
    width: 100% !important;
  }
  .h-screen, [class*="h-screen"] {
    height: auto !important;
    overflow: visible !important;
  }
}
</style>