<template>
  <div class="max-w-5xl mx-auto mt-2 pb-6">

    <div class="flex justify-content-between align-items-center mb-5">
      <div>
        <h1 class="m-0 text-gray-900 font-bold text-3xl">{{ $t('reports.title') }}</h1>
        <p class="text-gray-500 mt-1">{{ $t('reports.subtitle') }}</p>
      </div>
      <pv-button :label="$t('reports.generate_pdf')" icon="pi pi-file-pdf" @click="exportToPDF"
                 class="p-button-danger font-bold shadow-2" />
    </div>

    <pv-card class="shadow-1 border-none border-round-xl overflow-hidden">
      <template #title>
        <div class="px-3 pt-3 text-lg">{{ $t('reports.preview') }}</div>
      </template>
      <template #content>

        <div id="report-to-print" class="p-5 bg-white border-1 border-gray-100 border-round-lg">

          <div class="flex justify-content-between align-items-center border-bottom-2 border-gray-900 pb-4 mb-5">
            <img src="/logo.png" alt="Buildline" style="height: 40px;" />
            <div class="text-right">
              <div class="font-bold text-xl">REPORT: {{ $t('reports.inventory_report') }}</div>
              <div class="text-gray-500">Date: {{ currentDate }}</div>
            </div>
          </div>

          <div class="grid mb-5">
            <div class="col-4">
              <div class="p-3 border-1 border-gray-200 border-round-lg">
                <span class="block text-gray-500 text-sm mb-1">{{ $t('reports.items') }}</span>
                <span class="text-2xl font-bold">482</span>
              </div>
            </div>
            <div class="col-4">
              <div class="p-3 border-1 border-gray-200 border-round-lg">
                <span class="block text-gray-500 text-sm mb-1">Status</span>
                <span class="text-2xl font-bold text-green-600">Active</span>
              </div>
            </div>
            <div class="col-4">
              <div class="p-3 border-1 border-gray-200 border-round-lg">
                <span class="block text-gray-500 text-sm mb-1">{{ $t('reports.value') }}</span>
                <span class="text-2xl font-bold">$ 124,500</span>
              </div>
            </div>
          </div>

          <table class="w-full border-collapse">
            <thead>
            <tr class="bg-gray-100 text-left">
              <th class="p-3 border-bottom-2 border-gray-300">ID</th>
              <th class="p-3 border-bottom-2 border-gray-300">Material</th>
              <th class="p-3 border-bottom-2 border-gray-300">Project</th>
              <th class="p-3 border-bottom-2 border-gray-300 text-right">Stock</th>
            </tr>
            </thead>
            <tbody>
            <tr v-for="i in 5" :key="i" class="border-bottom-1 border-gray-100">
              <td class="p-3 text-sm">REQ-00{{i}}</td>
              <td class="p-3 text-sm font-medium">Steel Rebar 1/2"</td>
              <td class="p-3 text-sm">Skyline Tower</td>
              <td class="p-3 text-sm text-right">150</td>
            </tr>
            </tbody>
          </table>

          <div class="mt-8 text-center text-gray-400 text-xs">
            This is an automated document generated by Buildline Logistics Platform.
          </div>
        </div>

      </template>
    </pv-card>

  </div>
</template>

<script setup>
import { computed } from 'vue';

// Librería recomendada: html2pdf.js
// Para que funcione, primero debes ejecutar en tu terminal: npm install html2pdf.js
import html2pdf from 'html2pdf.js';

const currentDate = computed(() => new Date().toLocaleDateString());

const exportToPDF = () => {
  const element = document.getElementById('report-to-print');
  const opt = {
    margin:       [15, 15],
    filename:     'Buildline_Report.pdf',
    image:        { type: 'jpeg', quality: 0.98 },
    html2canvas:  { scale: 2, useCORS: true },
    jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
  };

  // Ejecuta la conversión
  html2pdf().set(opt).from(element).save();
};
</script>

<style scoped>
/* Estilos específicos para que el PDF se vea igual que en pantalla */
table { width: 100%; border-spacing: 0; }
th { font-weight: bold; }
</style>